### ISSUE TITLE
MountPath directory does not receive the correct permissions/ownership. 

### ISSUE THREAD

**Issue by robinAwallace** [UpCloudLtd/upcloud-csi#6]
When using specifying `securityContext` for a pod It is expected that the volume that is mounted to a path, `mountPath`, receives the correct permissions. As of now the directory is owned by `root:root` and not to the user the pod is running as.

The below is an example of a pod that mounts a pvc and creates a new directory in its `mountPath`. However it does not have the correct permissions as the pod is running as 1000:3000 fsGroup=2000. But the directory is owned by root(0):root(0).

The error:
```
mkdir: can't create directory '/data/test': Permission denied
```

```
kind: Pod
apiVersion: v1
metadata:
  name: csi-app
  labels:
    app: csi-app
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: upcloud-test-pod
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: upcloud-volume
      command: [ "mkdir", "/data/test" ]
  volumes:
    - name: upcloud-volume
      persistentVolumeClaim:
        claimName: csi-pvc
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: upcloud-block-storage
```
